### ISSUE TITLE
None of the Noto CJK fonts has a `dlng` entry in the `dataMap` in the `meta` table as [described](https://docs.microsoft.com/en-us/typography/opentype/spec/meta) here. This value is very useful to programmatically determine the script and language each font is most suitable for what language without having to encode Noto specific routines into the code base. Every other CJK font on the market has this entry. Most fonts have this unless it's a pan-unicode font. Please fix this.

### ISSUE THREAD

**Issue by wyuenho** [adobe-fonts/source-han-sans#270]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, JIS X 0208, JIS X 0212, and JIS X 0213 for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-sans/issues) and [closed](https://github.com/adobe-fonts/source-han-sans/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

As reported by #193 and #181, none of the Noto and Source Han Sans CJK fonts has a `dlng` entry in the `dataMap` in the `meta` table as [described](https://docs.microsoft.com/en-us/typography/opentype/spec/meta) here. This value is very useful to programmatically determine the script and language each font is most suitable for what language without having to encode Noto and Source Sans Han specific routines into the code base. Every other CJK font on the market has this entry. Most fonts have this unless it's a pan-unicode font.

This issue was claimed to be fixed in version 2, but 2.001 still doesn't have a meta table that contains these entries.

**Comment by punchcutter** [comment]
Sorry for the delay. This hasn't been forgotten, but didn't make it into the last release. Currently the plan is to get this into the next release.

**Comment by verdy-p** [comment]
All "Noto [Serif/Sans] [TC/SC/JP/KR]" (all 7 weights) have forgotten to include [dlng]/[slng] OpenType metadata.

As result, none of these fonts can be used in modern web browsers based on Chromium (including Google Chrome and MS Edge) and applications using web engines (with HTML+CSS) for their UI display. The [dlng]/[slng] metadata is now used isntead of the old (broken and very slow) font selection mechanisms based on parsing the character-to-glyph mappings, or older OS/2 metatables.

Any "Noto" font without [dlng]/[slng] are no longer usable on the web. Instead text renderers of web engines will try to use fallback fonts, and if there's none matching, will display "tofu".... That's clearly not what the "Noto" family was designed for when they wanted to avoid this situation. Those broken Noto fonts are only usable in rich-text documents or standalone applications that select a single explicit static font name and style, and not depending on dynamic font selection.

Please add the "[dlng]/[slng]" OpenType small metadata where it is missing in ALL Noto fonts. This is required now in modern web browsers and applications using web rendering engines. This omission is currently not checked in Google font test suites (that are still only testing the presence of legacy "OS/2" tables and similar bitmap metadata, no longer used by modern text rendering/shaping engines of modern browsers to select relevant fonts).
